Release 1
tests-always-included/ddq pull request #1
Opened 2016-09-21 20:28 UTC by AbsentSemicolon

This is the first release of DDQ. This includes all files to get it working except for a backend which is presenting still in Github.

Includes a few example scripts to see it in action provided the mock backend has been pulled in.

2016-09-21 20:29 UTC, garadox commented
You *may* want to consider squashing your commits.. :)

2016-09-21 20:31 UTC, garadox commented on README.md
> +Using DDQ is seprated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to
separated

2016-09-22 11:58 UTC, lnagle93 commented on README.md
> +This module was created because for the need of a system which acts like a queue for tasks but doesn't allow for duplication of those tasks. DDQ uses an `async` methodology to complete certain tasks,
'This module was created because for the need of a system' should be reworded. I'm assuming the 'for' was meant to be 'of'. 

In the second sentence, the phrase 'what happens when data is found to process' is a little wordy. Something along the lines of 'handling unprocessed data' might be better, assuming it is still an accurate description.

At the end of the third sentence, you have 'around' written twice.

2016-09-22 12:01 UTC, lnagle93 commented on README.md
> +DDQ also extends the Event Emitter module so it's very easy to use events for when there is data or error has occured and inform the software of these events.
There should be a comma after module.

There also needs to be an 'an' between 'or' and 'error'.

2016-09-22 12:13 UTC, lnagle93 commented on README.md
> +Using DDQ is seprated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to
The 'Using' at the beginning of the first sentence doesn't seem to be necessary.

2016-09-22 12:51 UTC, lnagle93 commented on README.md
> +Using DDQ is seprated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to
The first two sentences make it sound as though producer and consumer are components of DDQ. It should be made really clear that that isn't the case.

2016-09-22 12:52 UTC, AbsentSemicolon commented
@garadox The commits will be squashed when we merge the pull request. Github allows you to squash when merging.

2016-09-22 12:57 UTC, lnagle93 commented on README.md
> +Setting up DDQ is pretty straight forward. It does require some configuration to get everything working together. Your project would need to include DDQ in it's `package.json` and also include a `bac
Need a comma before 'so' in the last sentence.

2016-09-22 14:15 UTC, lnagle93 commented on README.md
> +Another config value is the `heartbeatDelay`. DDQ uses a method on the wrapped message, which we'll get to later which is called every so often to update the task/job in the queue that it's being pro
The second sentence is a little muddled, and doesn't seem totally necessary. Considering you do plan on talking about the method that utilizes `heartbeatDelay` later, the scope of this paragraph seems to be only mentioning that `heartbeatDelay` is a necessary component of a DDQ config and that its value is meant to represent milliseconds.

2016-09-22 14:17 UTC, lnagle93 commented on README.md
> +Also, servers might not be able to handle a certain number of processes, or you might only want to handle a few at a time, so setting the `maxProcessingMessages` to a number will make it so only up t
The 'then' in the last sentence should be 'than'.

2016-09-22 14:20 UTC, lnagle93 commented on README.md
> +    /* Pass in the config including which backend to use and DDQ will find it    * and use it.
Need a comma after config.

2016-09-22 14:21 UTC, lnagle93 commented on README.md
> +    /* Pass in the config including which backend to use and DDQ will find it    * and use it.
Also, and this may just be me misunderstanding, but there seems to be something wonky going on with the formatting of this line.

2016-09-22 14:23 UTC, AbsentSemicolon commented on README.md
> +    /* Pass in the config including which backend to use and DDQ will find it    * and use it.
This was caused by me setting my editor to use the print margin, so it lined up fine in the editor. I found another instance of this as well.

2016-09-22 14:32 UTC, AbsentSemicolon commented on README.md
> +Another config value is the `heartbeatDelay`. DDQ uses a method on the wrapped message, which we'll get to later which is called every so often to update the task/job in the queue that it's being pro
I see your point and realize I didn't talk about what happens when the data event is triggered. So I'll explain when that happens and include information about what the `heartbeatDelay` does.

2016-09-22 14:34 UTC, lnagle93 commented on README.md
> +At a point your consumer might want to pause the polling of messages so it can do a task without having messages coming at it. You can do this by simply calling a method withing DDQ called `pausePoll
First sentence: Should 'At a point' be 'At some point'?

Second sentence: 'calling a method withing DDQ called "pausePolling"'  should be changed to 'calling the DDQ method "pausePolling"'.

Third sentence: This has me a little puzzled. Will it work at all if you are not listening?

2016-09-22 14:37 UTC, lnagle93 commented on README.md
> +    // Telle the backend to resume polling.
Remove the second 'e' in tell.

2016-09-22 14:45 UTC, lnagle93 commented on examples/test-listener.js
> +        });
What might go inside of the callback above? This isn't necessarily a call to change anything in this code, more my own curiosity.

2016-09-22 14:53 UTC, fidian commented on examples/test-listener.js
> +        });
This would be a callback that indicates success or failure of sending the message.  The message sending bit is asynchronous and the preferred way of reporting back would be to use a callback.

This brings up a topic - callbacks should be optional.  @AbsentSemicolon would you audit the code and make sure that DDQ doesn't blindly call `callback`?  Instead, wrap it in an `if`.

    if (callback) {
        callback(err);
   }

2016-09-22 14:55 UTC, AbsentSemicolon commented on examples/test-listener.js
> +        });
Sure yeah, we call callback if it's supposed to be there, so I'll wrap them all in an if.

2016-09-22 15:09 UTC, lnagle93 commented on lib/ddq.js
> +const EMIT_DATA = "data", EMIT_ERROR = "error";
As a convention, are we okay with declaring all of the constants on one line? What if there are enough of them that they go past 80 characters?

2016-09-22 15:18 UTC, lnagle93 commented on lib/ddq.js
> + * Sets the messages being processed number back one number and checks to see
'Subtracts one from the number of messages being processed' might be better phrasing for this.

2016-09-22 15:19 UTC, lnagle93 commented on lib/ddq.js
> + * if the polling should be resumed if the limit is less then the max and the
Change 'then' to 'than'

2016-09-22 16:16 UTC, lnagle93 commented on lib/ddq.js
> +            if (!ddqInstance.isPausedByUser) {
Is this if block necessary if you set the condition `isPausedByLimts` to false everytime before you run it?

2016-09-22 16:18 UTC, lnagle93 commented on lib/ddq.js
> +function decrementMessagesBeingProcessed(ddqInstance) {
This function name only describes the first line inside its block. Perhaps `checkPollingConditions` would be a better alternative.

2016-09-22 16:34 UTC, lnagle93 commented on lib/ddq.js
> + * Sets the messages being processed up one and pauses the polling for the
Ditto our discussion earlier about whether or not this kind of documentation is necessary. If you determine it is, rephrasing to 'Increments the messages being processed by one' would be a bit more clear and concise.

2016-09-22 16:35 UTC, lnagle93 commented on lib/ddq.js
> +function incrementMessagesBeingProcessed(ddqInstance) {
Would be more accurate to name this function something along the lines of `checkPausingCondition` or `checkingPausePollingCondition`.

2016-09-22 16:38 UTC, lnagle commented on lib/ddq.js
> +         * TODO: Validate the config
If this isn't done, it should be noted in the issue log rather than commented in the code, right?

2016-09-22 16:39 UTC, lnagle93 commented on lib/ddq.js
> +                throw new Error("No Config was passed.");
Config doesn't need to be capitalized here.

2016-09-22 16:42 UTC, lnagle93 commented on lib/ddq.js
> +            this.messagesBeingProcessed = 0;
Not a convention as far as I know, and I'm getting pretty damn nitpicking here, but for the sake of OCD these could be alphabetized.

2016-09-22 16:43 UTC, lnagle93 commented on lib/ddq.js
> +         * instance has made so we don't have connections to keep running.
Need a comma before 'so'.

2016-09-22 16:46 UTC, lnagle93 commented on lib/ddq.js
> +         * Pauses the polling for until started up again. This
The 'for' in this sentence is unnecessary.

2016-09-22 16:50 UTC, lnagle93 commented on lib/ddq.js
> +         * functionality once the message is sent.
This last sentence is unclear to me. Is there a way of rephrasing 'to do functionality'?

2016-09-22 17:06 UTC, lnagle93 commented on spec/lib/ddq.spec.js
> +            ddq = new Ddq(config);
These lines don't seem to be necessary, what with your setup in the beforeEach.

2016-09-22 17:08 UTC, lnagle93 commented on spec/lib/ddq.spec.js
> +            ddq = new Ddq(config);
This and line 237 are unnecessary.

2016-09-22 17:09 UTC, lnagle93 commented on spec/lib/ddq.spec.js
> +            ddq = new Ddq(config);
The above three lines can be removed.

2016-09-22 17:13 UTC, lnagle93 commented on spec/lib/ddq.spec.js
> +        it("sets the polling is paused in the process of doing a heartbeat", (done) => {
The wording here is a little confusing. If you're referring to the isPausedByUser property, you should say that explicity. Ie "sets the ddq.isPausedByUser in the process of doing a heartbeat".

2016-09-22 17:15 UTC, lnagle commented on spec/lib/ddq.spec.js
> +        it("removes the message but emits the callback was done repeatedly", (done) => {
Should there be a 'that' between 'emits' and 'the'?

2016-09-22 17:18 UTC, lnagle93 commented on spec/lib/ddq.spec.js
> +            errorCalled = false;
errorCalled could be set in the beforeEach for this and the above test.

2016-09-22 17:25 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            ddq = new Ddq(config);
You're right, not needed.

2016-09-22 17:27 UTC, lnagle93 commented on spec/lib/ddq.spec.js
> +            ddq = new Ddq(config);
`ddq` can be declared on line 4 and `ddq = new Ddq(config)` can be run above line 19. All other declarations of `var ddq` and `ddq = new Ddq(config)` can be removed.

2016-09-22 17:29 UTC, lnagle93 commented on spec/mock/timers.mock.js
> +"use strict";
Should this filed be called `spec/mock/timers-mock.js` rather than `spec/mock/timers.mock.js`?

2016-09-22 17:29 UTC, lnagle93 commented on spec/mock/timers.mock.js
> +mock = jasmine.createSpyObj("mockTimers", [
`mockTimers` should be `timersMock`.

2016-09-22 17:33 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            errorCalled = false;
Put the setting of this to false in the before to make sure we get a clean variable for each test when used.

2016-09-22 17:35 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            ddq = new Ddq(config);
We change the options passed to config for certain tests and we want to be able to show someone coming into the tests exactly what's going on. Having ddq set up that early in the testing could get confusing later on about what tests are doing.

2016-09-22 17:36 UTC, AbsentSemicolon commented on spec/mock/timers.mock.js
> +"use strict";
yep, that's probably better to do.

2016-09-22 17:47 UTC, AbsentSemicolon commented on spec/mock/timers.mock.js
> +mock = jasmine.createSpyObj("mockTimers", [
I agree

2016-09-22 17:48 UTC, AbsentSemicolon commented on lib/ddq.js
> +         * functionality once the message is sent.
I rephrased this to be like what we talked about, just simplified some of the JsDocs.

2016-09-22 17:49 UTC, AbsentSemicolon commented on lib/ddq.js
> +            this.messagesBeingProcessed = 0;
Yep sounds good/better to have it alphabetized.

2016-09-23 11:26 UTC, lnagle93 commented on README.md
> +When the `data` is done processing the callback will be called and DDQ will take action whether the software told it was successful or not. First the `heartbeatKill` method will be called. This tells
Last sentence: I think you meant 'separation of work'.

2016-09-23 11:32 UTC, lnagle93 commented on README.md
> +Another config value is the `heartbeatDelay`. DDQ uses a method on the wrapped message, which we'll get to later which is called every so often to update the task/job in the queue that it's being pro
Did you mean to remove the second sentence in your first batch of changes, or did you decide it would be best left as it is?

2016-09-23 11:33 UTC, lnagle commented on README.md
> +Using DDQ is seprated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to
Looks like this was never addressed in your changes.

2016-09-23 11:35 UTC, lnagle93 commented on lib/ddq.js
> + * Subtracts one from the number of messages being processed checks if
Need an 'and' between 'processed' and 'checks'.

2016-09-23 11:39 UTC, lnagle93 commented on lib/ddq.js
> +function decrementMessagesBeingProcessed(ddqInstance) {
This and the similar comment about the 'incrementMessageBeingProcessed' function were never addressed in your changes.

2016-09-23 11:43 UTC, lnagle93 commented on lib/ddq.js
> +         * Tells the backend to pauses the polling. This can be used if
'pauses' should be 'pause'.

2016-09-23 12:38 UTC, AbsentSemicolon commented on lib/ddq.js
> +         * Tells the backend to pauses the polling. This can be used if
Corrected

2016-09-23 12:39 UTC, AbsentSemicolon commented on lib/ddq.js
> + * Subtracts one from the number of messages being processed checks if
Corrected

2016-09-23 12:40 UTC, AbsentSemicolon commented on README.md
> +When the `data` is done processing the callback will be called and DDQ will take action whether the software told it was successful or not. First the `heartbeatKill` method will be called. This tells
Corrected

2016-09-23 12:40 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +        it("sets the polling is paused in the process of doing a heartbeat", (done) => {
Fixed

2016-09-23 12:43 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +        it("removes the message but emits the callback was done repeatedly", (done) => {
Corrected

2016-09-23 12:44 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            ddq = new Ddq(config);
Removed

2016-09-23 12:45 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            ddq = new Ddq(config);
Removed

2016-09-23 12:48 UTC, AbsentSemicolon commented on lib/ddq.js
> +         * Pauses the polling for until started up again. This
Wording changed to better descrbe.

2016-09-23 12:48 UTC, AbsentSemicolon commented on lib/ddq.js
> +         * instance has made so we don't have connections to keep running.
Added

2016-09-23 12:48 UTC, AbsentSemicolon commented on lib/ddq.js
> +                throw new Error("No Config was passed.");
Nope it doesn't

2016-09-23 12:50 UTC, AbsentSemicolon commented on lib/ddq.js
> +         * TODO: Validate the config
Made an issue for this and removed the todo.

2016-09-23 13:39 UTC, AbsentSemicolon commented on lib/ddq.js
> +function incrementMessagesBeingProcessed(ddqInstance) {
Renamed to `incrementProcessingMessagesAndPausePolling`

2016-09-23 13:39 UTC, AbsentSemicolon commented on lib/ddq.js
> +function decrementMessagesBeingProcessed(ddqInstance) {
Changed to `decrementProcessingMessagesAndResumePolling`

2016-09-23 13:39 UTC, AbsentSemicolon commented on lib/ddq.js
> + * if the polling should be resumed if the limit is less then the max and the
Corrected

2016-09-23 13:40 UTC, AbsentSemicolon commented on lib/ddq.js
> + * Sets the messages being processed number back one number and checks to see
Corrected

2016-09-23 13:42 UTC, AbsentSemicolon commented on README.md
> +Using DDQ is seprated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to
Yeah, I've removed it, doesn't make sense.

2016-09-23 13:42 UTC, AbsentSemicolon commented on README.md
> +Using DDQ is seprated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to
Removed

2016-09-23 13:42 UTC, AbsentSemicolon commented on README.md
> +DDQ also extends the Event Emitter module so it's very easy to use events for when there is data or error has occured and inform the software of these events.
added

2016-09-23 13:42 UTC, AbsentSemicolon commented on README.md
> +This module was created because for the need of a system which acts like a queue for tasks but doesn't allow for duplication of those tasks. DDQ uses an `async` methodology to complete certain tasks,
Corrected issues here.

2016-09-23 13:42 UTC, AbsentSemicolon commented on README.md
> +Using DDQ is seprated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to
Fixed.

2016-09-23 16:03 UTC, fidian commented on spec/lib/ddq.spec.js
> +            wrappedMessage = mockRequire.reRequire("../mock/wrapped-message-mock");
Why?  I see no reason for this.  Also, consider changing this to a factory.

2016-09-23 16:04 UTC, fidian commented on spec/lib/ddq.spec.js
> +                    if (!wrappedMessage.called) {
This looks bad.  You should be able to track if something was called pretty easily using spies.  You don't need a counter or boolean.

2016-09-23 16:05 UTC, fidian commented on spec/mock/timers-mock.js
> +mock.clearInterval.andCallFake((callback) => {
Do you use all of these exposed methods?

2016-09-23 16:05 UTC, fidian commented on spec/mock/wrapped-message-mock.js
> +mock.called = false;
This should be removed.

2016-09-23 16:06 UTC, fidian requested changes
Difficult for me to review when GitHub tells me this page is out of date due to the pushes that were happening.  Next time I would prefer to only be reviewing when the code is not in flux.

2016-09-23 16:06 UTC, fidian commented on .eslintrc.yaml
> +    - eslint:recommended
Add a space after the colon.

2016-09-23 16:06 UTC, fidian commented on README.md
> +This module was created because of a need for a system which acts like a queue for tasks but doesn't allow for duplication. DDQ uses an `async` methodology to complete certain tasks, like sending mes
Promises are capitalized.

"sending messages and what happens when data is found to process" -> "sending and receiving messages, then indicating that the message has been fully processed"

"easier to get around" may be better worded as "easier to integrate with other libraries".

2016-09-23 16:06 UTC, fidian commented on README.md
> +DDQ also extends the Event Emitter module so it's very easy to use events for when there is data or an error has occured and inform the software of these events.
Change "data" to "a message".

Add a paragraph about how the queue system will mark messages as being processed and effectively "locks" the message during processing.  During that time another identical message may be queued and it won't be acted upon until after the first one is completed.  Additional wording as is necessary.

2016-09-23 16:06 UTC, fidian commented on README.md
> +A couple terms which are used in these docs and could be within the code are `producer` and `consumer`. The `producer` is the software creating tasks; the one which sends messages to DDQ to put into
I think that this paragraph can be omitted.  We don't care about what sends and receives messages.

2016-09-23 16:06 UTC, fidian commented on README.md
> +DDQ is separated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to take
This section isn't "Usage", it is more of the "About" section.  Maybe reword this and only focus on the DDQ vs backend separation.

DDQ is split into this core library and a backend.  The core exposes the public interface, initializes the backend, then encapsulates some of the logic (such as message heartbeats) so the backends have less duplicated code.  The backend is responsible for implementation-level details, such as how to store and retrieve messages and the queue cleanup jobs.  The backend is specific to a data source, such as MySQL.

2016-09-23 16:06 UTC, fidian commented on README.md
> +Setting up DDQ is pretty straight forward. It does require some configuration to get everything working together. Your project would need to include DDQ in it's `package.json` and also include a `bac
Change "In the `config` value for `backend` this" to "The `backendConfig` value".

`node_modules` should include `/` at the end for consistency.

2016-09-23 16:06 UTC, fidian commented on README.md
> +Another config value is the `heartbeatDelay`. DDQ uses a method on the wrapped message, which we'll get to later which is called every so often to update the task/job in the queue that it's being pro
Don't have "which" in a sentence twice.  Change "which is called" to ".  A heartbeat routine is called"

"This would set that update ..." -> "The `heartbeatDelay` is configured in milliseconds, so a value of "1000" would have the heartbeat execute every second."

2016-09-23 16:06 UTC, fidian commented on README.md
> +    var DeDuplicatedQueue, deduplicatedQueue;
I would suggest changing `deduplicatedQueue` to `instance` to make it clear.

2016-09-23 16:06 UTC, fidian commented on README.md
> +     * and use it.
Add a note saying something like "You must list the backend in your package.json file and it must be installed for this example to work."  Alternately, you could provide a sample `package.json` file or sample `npm --save install ddq ddq-backend-mysql` to get a project off the ground.

2016-09-23 16:06 UTC, fidian commented on README.md
> +Setting Up
Additional spare newline needed above headings.  Two blank lines above each heading except the first heading in the file.

2016-09-23 16:06 UTC, fidian commented on README.md
> +A producer would be one to send a message. Using the `sendMessage` method you would send in the `message` you want to use and a `callback`. The callback is a way to handle when the `message` is succe
Strike comment about "producer".  Describe this by the intent that the user wants to happen.  Eg. "To send a message into the queue, use `instance.sendMessage()`.  You pass in the message and an optional callback that will be executed once the message has been sent."

2016-09-23 16:06 UTC, fidian commented on README.md
> +Once you have an instance of DDQ, you then need to `listen` to events which will be emitted from it. DDQ will send two types of events, `data` and `error`. When `data` is emitted you'll receive a mes
You don't need to listen if you have an instance - the wording in the first sentence implies that one MUST listen for events even if they don't want to receive messages.

"In order to receive messages from the queue, call `instance.listen()` and the `instance` will start to emit messages as they are found."

2016-09-23 16:06 UTC, fidian commented on README.md
> +When the `data` event is triggered from the backend DDQ will use methods on the data received from the `backend`. These methods include: `heartbeat`, `heartbeatKill`, `requeue`, and `remove`. The onl
`heartbeatKill` should not exist.  This paragraph is better moved to the backend documentation - consumers of this library (both "producers" and "consumers" per your definitions above) won't care.

2016-09-23 16:06 UTC, fidian commented on README.md
> +When the `data` is done processing the callback will be called and DDQ will take action whether the software told it was successful or not. First the `heartbeatKill` method will be called. This tells
Separate this into stuff people care about when using DDQ and stuff the backend implementors care about, then move the backend stuff to dedicated documentation.

Remove backticks on `backend`.  Methods should have `parenthesis()` or be `instance.method()`.  (here and basically everywhere)

2016-09-23 16:06 UTC, fidian commented on README.md
> +
Drop one line here.

2016-09-23 16:06 UTC, fidian commented on README.md
> +            callback(new Error("Something bad happened"));
Add a comment here saying that the message will be requeued for later processing.

2016-09-23 16:06 UTC, fidian commented on README.md
> +            callback();
Add a comment here saying the message will be removed from the queue.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +            this.backend.pausePolling();
Should only pause if we are listening.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +                    this.backend.resumePolling();
Should only resume if we were listening.

2016-09-23 16:06 UTC, fidian commented on README.md
> +At some point your consumer might want to pause the polling of messages so it can do a task without having messages coming at it. You can do this by simply calling the DDQ method `pausePolling`. This
Why doesn't pause work when you are not listening for events?  Does it still work if you pause and then call listen?  Would the backend be paused still?  I've flagged the code.  This one sentence about "only works" should be removed.

Implementation details such as `pausedByUser` should be removed from this document.  The end user doesn't care.

Remove the backticks on listener.

2016-09-23 16:06 UTC, fidian commented on README.md
> +Pausing
Pausing what?  Why not call this "Pausing and Resuming Polling" since the functionality is so tightly linked?

2016-09-23 16:06 UTC, fidian commented on README.md
> +Once you feel you should resume polling you can call the `resumePolling` method. This will set the flag `pausedByUser` back to false and check if the `pausedByLimits` flag was set before telling the
Remove the bit about the flags.

`listener` is in a code thing, yet it is not code.  Remove the backticks.

2016-09-23 16:06 UTC, fidian commented on README.md
> +At some time you'll want to stop listening to DDQ which you will call `close`. This will call the backend to close it's connections and emitting.
... "and emitting" -> ", stop polling for messages and stop emitting messages."

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +        destroy() {
JS doesn't have destructors.  Just found that out.  :-(

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +            super();
Is this necessary with ES6?

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +            this.backend.close(callback);
What if the backend was not open?

What happens to messages that are being processed?  I don't think we need to add code here.  Maybe just document that they can still process successfully even though you aren't listening for things.

ALSO, the backend configuration needs to know that `.close()` may not necessarily mean to close the database connections.  I think we may want to separate the two things - database connections from event polling.  Connections would be things like open DB, close DB.  Polling is start, stop.  Maybe that is something we should talk about.

2016-09-23 16:06 UTC, fidian commented on examples/test-listener.js
> +timers = require("timers");
Move `require()` calls to the top, just under `var`;

2016-09-23 16:06 UTC, fidian commented on examples/test-listener.js
> +ddq.on("error", () => {
Can we log the error that is passed to this event too?

2016-09-23 16:06 UTC, fidian commented on examples/test-listener.js
> +        });
Like 50 should not have a newline after the open brace.

2016-09-23 16:06 UTC, fidian commented on examples/test-listener.js
> +/* eslint no-process-exit:0 */
Where do you call process.exit()?

2016-09-23 16:06 UTC, fidian commented on examples/test-send-message.js
> +/* eslint no-process-exit:0 */
Where do you call process.exit()?

2016-09-23 16:06 UTC, fidian commented on examples/test-send-message.js
> +Ddq = require("../lib/index.js");
Move `require()` to just under `var`

Change to `Ddq = require("..");` and you would notice a problem with the `package.json` (flagged separately).

2016-09-23 16:06 UTC, fidian commented on examples/test-send-message.js
> +    console.log("Message Sent");
Should be placed in the `else` side of the `if` statement.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> + * @typeDef {Object} Ddq~backendConfig
Do not document here.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> + * @property {Ddq~backendConfig} backendConfig
Change to `{Object}`

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> + * @proprety {interger} messagesBeingProcessed
Typo.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> + * @property {Function} requeue
Missing `heartbeat`

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +const EMIT_DATA = "data", EMIT_ERROR = "error";
Ug.  Probably should use the "newline after comma" rule.  I'll update style guide.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> + * Subtracts one from the number of messages being processed checks if
Period after "processed" then capitalize "Checks".

Suggest you rewrite the description after what action it is supposed to perform from a story point of view, not a code point of view, then rename the function.

> Signals that a message is done being processed.
> 
> When we were at our limit of simultaneous messages being processed,
> this will start the backend up and let it poll again for more messages.

That would work for `messageCompleted()`.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> + * Sets up and clears the heartbeat for a particular message.
> Starts a loop to repeatedly call a message's heartbeat function.
> Returns a function that will clear the heartbeat.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +function decrementMessagesBeingProcessed(ddqInstance) {
This function and the rest should all be in your factory function so they have access to the global dependencies.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> + * Adds one to the messages being processed property and checks if polling
Again, you wrote the description from the point of view of a programmer.  What would a BA say this portion of code is responsible for doing?

> Updates counters to indicate another message is being processed.
> If we are at our limit, this pauses the backend's polling for more messages.

`messageBeingProcessed()` or similar?

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +    /**
In case you were wondering, I would move the functions to right here.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +            this.config = config;
This property should not be used and I don't think it is actually used.

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +            /* Just want to send the error event to the caller. The caller
"to the caller" is inaccurate.  How about removing those words and change "send" to "relay"?  Then change "The caller" to "Another listener".

2016-09-23 16:06 UTC, fidian commented on lib/ddq.js
> +         * Resumes polling if conditions agree.
What are those conditions, as told from a user story point of view?  This function also takes an action and may flip a boolean, but that's not really indicated from this comment.

2016-09-23 16:06 UTC, fidian commented on package.json
> +  "private": false,
Omit.

2016-09-23 16:06 UTC, fidian commented on examples/test-listener.js
> +Ddq = require("../lib/index.js");
Change to `Ddq = require("..");` and you would notice a problem with the `package.json` (flagged separately).

2016-09-23 16:06 UTC, fidian commented on package.json
> +  "main": "lib/ddq.js",
Should be "lib/" or "lib/index.js"

2016-09-23 16:06 UTC, fidian commented on package.json
> +    "ddq-backend-mock": "git://github.com/AbsentSemicolon/ddq-backend-mock.git#develop",
Use the published one.  Hold on this until the mock is pushed and published.

2016-09-23 16:06 UTC, fidian commented on package.json
> +}
Add "keywords"

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +                new Ddq(config);
Remove the eslint stuff and have the line read

```
return new Ddq(config);
```

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +                // eslint-disable-next-line no-new
Same here.

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +        it("fails closing the polling when calling backend to close", () => {
There is no failure here.  Description is wrong.

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +    describe(".destroy()", () => {
Delete.  Sorry.

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +        beforeEach(() => {
Should wrap the "error event" and "data event" tests together.

```
describe("EventEmitter", () => {
    beforeEach(() => {
        ... stuff
    });
    describe("error event", () => {
        // no beforeEach() is needed
        it("....", () => {...
```

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +        afterEach(() => {
Why is this necessary?

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +            expect(wrappedMessage.heartbeatKill).not.toHaveBeenCalled();
This function should never exist.

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +            done();
Thinking this code should change the trigger to allow for async events in DDQ.

```
ddq.pausePolling();
ddq.on("data", jasmine.fail);
wrappedMessage.requeue.andCallFake(() => {
    done();
});
```

That seems much simpler to me.  If the data is ever emitted the test will fail.  If the message is immediately requeued, the test passes.  If something else happens, the test fails after a few seconds.

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +            ddq.on("error", (callback) => {
What is this doing??

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +                done();
Is this test async or sync?  You can call done three different places.  :-(

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +                done();
Same here - async or sync test?

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +                done();
Same here - async or sync test?

I'm done flagging this.  Each test should have one `done()` call, ever.

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +            expect(wrappedMessage.remove).toHaveBeenCalled();
This should only be done before `done()`.

You should make sure it was called one time.

2016-09-23 16:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +                done();
This call to `done()` should not be here.

2016-09-23 16:39 UTC, AbsentSemicolon commented on README.md
> +This module was created because of a need for a system which acts like a queue for tasks but doesn't allow for duplication. DDQ uses an `async` methodology to complete certain tasks, like sending mes
Sounds better, thanks for the edit.

2016-09-23 16:40 UTC, AbsentSemicolon commented on README.md
> +A couple terms which are used in these docs and could be within the code are `producer` and `consumer`. The `producer` is the software creating tasks; the one which sends messages to DDQ to put into
Yeah, doesn't really make sense to have it.

2016-09-23 16:47 UTC, fidian commented
Heartbeats that fail because the message was removed should not trigger error events to whatever is listening to DDQ.

2016-09-23 16:48 UTC, AbsentSemicolon commented on README.md
> +Setting Up
Corrected

2016-09-23 16:52 UTC, AbsentSemicolon commented on README.md
> +Another config value is the `heartbeatDelay`. DDQ uses a method on the wrapped message, which we'll get to later which is called every so often to update the task/job in the queue that it's being pro
Sounds a lot better.

2016-09-23 18:23 UTC, AbsentSemicolon commented on README.md
> +When the `data` event is triggered from the backend DDQ will use methods on the data received from the `backend`. These methods include: `heartbeat`, `heartbeatKill`, `requeue`, and `remove`. The onl
Removed heartbeatKill and moved the paragraph to the backend doc.

2016-09-23 18:30 UTC, AbsentSemicolon commented on README.md
> +Pausing
Combined pausing and resuming

2016-09-23 18:32 UTC, AbsentSemicolon commented on README.md
> +At some time you'll want to stop listening to DDQ which you will call `close`. This will call the backend to close it's connections and emitting.
Sounds better.

2016-09-23 18:33 UTC, AbsentSemicolon commented on lib/ddq.js
> + * @typeDef {Object} Ddq~backendConfig
Yeah, makes sense.

2016-09-23 18:33 UTC, AbsentSemicolon commented on lib/ddq.js
> + * @property {Ddq~backendConfig} backendConfig
Since we aren't documenting the backend config we don't need that defined anymore.

2016-09-23 18:34 UTC, AbsentSemicolon commented on lib/ddq.js
> + * @property {Function} requeue
Strange, swore this was in there. Well it's there now.

2016-09-23 18:35 UTC, AbsentSemicolon commented on lib/ddq.js
> + * @proprety {interger} messagesBeingProcessed
Yep, should have been number.

2016-09-23 18:44 UTC, AbsentSemicolon commented on lib/ddq.js
> +function decrementMessagesBeingProcessed(ddqInstance) {
Moved these inside the factory.

2016-09-23 18:46 UTC, AbsentSemicolon commented on lib/ddq.js
> +    /**
Got it, moved them. Thanks.

2016-09-23 19:00 UTC, AbsentSemicolon commented on lib/ddq.js
> +            super();
This is because I want to use this, which `super()` seems to define.

2016-09-23 19:01 UTC, AbsentSemicolon commented on lib/ddq.js
> +            this.config = config;
Right it's not used anymore.

2016-09-23 20:20 UTC, AbsentSemicolon commented on lib/ddq.js
> +        destroy() {
Remove this from the code.

2016-09-23 20:33 UTC, AbsentSemicolon commented on lib/ddq.js
> +            this.backend.pausePolling();
Added this.isListening.

2016-09-23 20:36 UTC, AbsentSemicolon commented on lib/ddq.js
> +                    this.backend.resumePolling();
Updated logic to include this.isListening

2016-09-23 20:36 UTC, AbsentSemicolon commented on lib/ddq.js
> +         * Resumes polling if conditions agree.
Updated comment to include what it's actually doing.

2016-09-26 14:04 UTC, AbsentSemicolon commented on examples/test-listener.js
> +timers = require("timers");
Makes sense.

2016-09-26 14:05 UTC, AbsentSemicolon commented on examples/test-listener.js
> +/* eslint no-process-exit:0 */
I don't this was to prevent eslint to stop looking for it. But apparently it's not needed anymore.

2016-09-26 14:11 UTC, AbsentSemicolon commented on examples/test-listener.js
> +Ddq = require("../lib/index.js");
Yeah I see the issue. This is corrected now.

2016-09-26 14:12 UTC, AbsentSemicolon commented on examples/test-listener.js
> +ddq.on("error", () => {
Good catch.

2016-09-26 14:17 UTC, AbsentSemicolon commented on examples/test-send-message.js
> +/* eslint no-process-exit:0 */
I don't, this was to prevent eslint from complaining, but taking it out doesn't make a difference so it's not needed after all.

2016-09-26 14:17 UTC, AbsentSemicolon commented on examples/test-send-message.js
> +Ddq = require("../lib/index.js");
See the issue and it's fixed.

2016-09-26 14:18 UTC, AbsentSemicolon commented on examples/test-send-message.js
> +    console.log("Message Sent");
Yeah, it should have been there.

2016-09-26 14:18 UTC, AbsentSemicolon commented on package.json
> +  "main": "lib/ddq.js",
Changed to be `lib/index.js`.

2016-09-26 14:19 UTC, AbsentSemicolon commented on package.json
> +  "private": false,
ok

2016-09-26 14:23 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +                new Ddq(config);
That worked better.

2016-09-26 14:23 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +                // eslint-disable-next-line no-new
Ditto

2016-09-26 14:24 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +    describe(".destroy()", () => {
Deleted.

2016-09-26 14:26 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            expect(wrappedMessage.heartbeatKill).not.toHaveBeenCalled();
Removed

2016-09-26 14:29 UTC, AbsentSemicolon commented on spec/mock/timers-mock.js
> +mock.clearInterval.andCallFake((callback) => {
Nope, took out the ones not needed.

2016-09-26 15:21 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            wrappedMessage = mockRequire.reRequire("../mock/wrapped-message-mock");
Changed to a factory and works a lot better.

2016-09-26 16:56 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +                    if (!wrappedMessage.called) {
Using the `callcount` for the method was much better.

2016-09-26 16:56 UTC, AbsentSemicolon commented on spec/mock/wrapped-message-mock.js
> +mock.called = false;
took it out, using `callCount` now.

2016-09-26 17:01 UTC, AbsentSemicolon commented
What should an error on heartbeat do? Should we put a logging module in to just log the error?

2016-09-26 17:01 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +                done();
Got just one done now in all places where I believe it should go.

2016-09-26 17:01 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +                done();
Got just one done now in all places where I believe it should go.

2016-09-26 17:01 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +                done();
Got just one done now in all places where I believe it should go.

2016-09-26 17:02 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            ddq.on("error", (callback) => {
Renamed test to make more sense for what's going on.

2016-09-26 17:21 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            done();
Yeah, this works and cleans up the test a bit.

2016-09-26 17:22 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +        afterEach(() => {
was having trouble getting the tests to work properly so was using it clean up things set, but making wrapped message a factory made this easier to work with.

2016-09-26 17:25 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +        it("fails closing the polling when calling backend to close", () => {
Yeah the description was wrong.

2016-09-26 17:32 UTC, AbsentSemicolon commented on lib/ddq.js
> +            /* Just want to send the error event to the caller. The caller
That makes a lot more sense.

2016-09-26 17:47 UTC, AbsentSemicolon commented on lib/ddq.js
> + * Sets up and clears the heartbeat for a particular message.
Updated with comment

2016-09-26 17:47 UTC, AbsentSemicolon commented on lib/ddq.js
> + * Adds one to the messages being processed property and checks if polling
Updated this to better clarify from a BA stand point.

2016-09-26 17:47 UTC, AbsentSemicolon commented on lib/ddq.js
> + * Subtracts one from the number of messages being processed checks if
Updated with comment.

2016-09-26 18:25 UTC, AbsentSemicolon commented on README.md
> +Setting up DDQ is pretty straight forward. It does require some configuration to get everything working together. Your project would need to include DDQ in it's `package.json` and also include a `bac
`/` added.

2016-09-26 18:26 UTC, AbsentSemicolon commented on README.md
> +    var DeDuplicatedQueue, deduplicatedQueue;
Made this instance... it does make it clearer.

2016-09-26 18:26 UTC, AbsentSemicolon commented on README.md
> +            callback(new Error("Something bad happened"));
Comment added

2016-09-26 18:26 UTC, AbsentSemicolon commented on README.md
> +
Got rid of line.

2016-09-26 18:26 UTC, AbsentSemicolon commented on README.md
> +            callback();
Added comment

2016-09-26 18:27 UTC, AbsentSemicolon commented on README.md
> +At some point your consumer might want to pause the polling of messages so it can do a task without having messages coming at it. You can do this by simply calling the DDQ method `pausePolling`. This
Updated to take in advice.

2016-09-26 18:27 UTC, AbsentSemicolon commented on README.md
> +Once you feel you should resume polling you can call the `resumePolling` method. This will set the flag `pausedByUser` back to false and check if the `pausedByLimits` flag was set before telling the
Removed flags and backticks.

2016-09-26 18:38 UTC, AbsentSemicolon commented on README.md
> +A producer would be one to send a message. Using the `sendMessage` method you would send in the `message` you want to use and a `callback`. The callback is a way to handle when the `message` is succe
Updated

2016-09-26 18:38 UTC, AbsentSemicolon commented on README.md
> +Once you have an instance of DDQ, you then need to `listen` to events which will be emitted from it. DDQ will send two types of events, `data` and `error`. When `data` is emitted you'll receive a mes
Updated

2016-09-26 18:39 UTC, AbsentSemicolon commented on README.md
> +DDQ is separated into parts and each component of it is strict on what it does. The `producer` and `consumer` we've already talked about. So there is DDQ and it's `backend` left. DDQ's job is to take
I just removed usage and moved things into approprate areas. Setting up is basically usage.

2016-09-26 18:39 UTC, AbsentSemicolon commented on README.md
> +DDQ also extends the Event Emitter module so it's very easy to use events for when there is data or an error has occured and inform the software of these events.
Changed and added.

2016-09-26 18:42 UTC, AbsentSemicolon commented on lib/ddq.js
> +const EMIT_DATA = "data", EMIT_ERROR = "error";
I made eslintrc.yaml error when constants are on the same line.

    one-var:
        - error
        -
            const: never

2016-09-26 18:43 UTC, AbsentSemicolon commented on README.md
> +     * and use it.
Added saying it needs to be in package.json

2016-09-26 18:43 UTC, AbsentSemicolon commented on README.md
> +When the `data` is done processing the callback will be called and DDQ will take action whether the software told it was successful or not. First the `heartbeatKill` method will be called. This tells
Added parens

2016-09-26 19:46 UTC, fidian commented on lib/ddq.js
> +            super();
Doh, I screwed up.

2016-09-26 19:47 UTC, fidian commented on .eslintrc.yaml
> +    - eslint:recommended
And a newline before eslint:

See the style guide and the JS section.  It has a link to a fixed .eslintrc.yaml file.

2016-09-26 19:54 UTC, fidian commented on lib/ddq.js
> +            this.backend.close(callback);
File this as an issue.

2016-09-26 20:08 UTC, AbsentSemicolon commented on lib/ddq.js
> +            this.backend.close(callback);
Issue #4 opened for this.

2016-09-26 20:08 UTC, AbsentSemicolon commented on package.json
> +}
added

2016-09-27 17:53 UTC, lnagle93 commented on README.md
> +In order to receive messages from the queue, call `instance.listen()` and the instance will start to emit messages as they are found. DDQ will send two types of events: `data` and `error`. When `data
'When `data` is emitted' is ended prematurely with a period where there should be comma.

2016-09-27 17:55 UTC, lnagle93 commented on README.md
> +At some time you'll want to stop listening to DDQ which you will call `close`. This will call the backend to close it's connections and, stop polling for messages and stop emitting messages..
Remove the first 'and' in the second sentence.

2016-09-27 17:57 UTC, lnagle commented on examples/test-listener.js
> +Ddq = require("..");
Is this a valid path?

2016-09-27 17:57 UTC, lnagle93 commented on examples/test-listener.js
> +        console.log(`There was an error sendin message: message_${i}`);
There should be a 'g' at the end of 'sendin'.

2016-09-27 18:35 UTC, AbsentSemicolon commented on examples/test-listener.js
> +Ddq = require("..");
Yes it is.

2016-09-27 18:38 UTC, AbsentSemicolon commented on README.md
> +In order to receive messages from the queue, call `instance.listen()` and the instance will start to emit messages as they are found. DDQ will send two types of events: `data` and `error`. When `data
You're right, should have been a comma.

2016-09-27 18:38 UTC, AbsentSemicolon commented on README.md
> +At some time you'll want to stop listening to DDQ which you will call `close`. This will call the backend to close it's connections and, stop polling for messages and stop emitting messages..
That shouldn't be there.

2016-09-27 18:38 UTC, AbsentSemicolon commented on examples/test-listener.js
> +        console.log(`There was an error sendin message: message_${i}`);
Yep, I caught that when working on the ddq backend.

2016-09-27 19:06 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +            expect(wrappedMessage.remove).toHaveBeenCalled();
It is.

2016-09-27 19:06 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +                done();
Removed this.

2016-09-27 19:06 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +        beforeEach(() => {
These are together now.

2016-09-27 19:07 UTC, AbsentSemicolon commented on package.json
> +    "ddq-backend-mock": "git://github.com/AbsentSemicolon/ddq-backend-mock.git#develop",
I'll have another pull request when ddq backend mock gets published.

2016-09-27 19:14 UTC, fidian requested changes
Oh, the awesome!
One thing to fix.

2016-09-27 19:14 UTC, fidian commented on spec/lib/ddq.spec.js
> +                    emitted = true;
Can this test be converted to a `done()` callback?

2016-09-27 19:21 UTC, AbsentSemicolon commented on spec/lib/ddq.spec.js
> +                    emitted = true;
Done and fixed.

2016-09-27 19:22 UTC, fidian commented
Do it up.

2016-09-27 19:23 UTC, merged