Release1.1
tests-always-included/ddq pull request #6
Opened 2016-10-31 16:37 UTC by lnagle93

This task encompasses several changes that need to be made to DDQ. These include:
 - DDQ should instantiate the Plugin.
 - DDQ should determine when the Plugin has or does not have a connection to the database.
 - Updating and improving the naming conventions of some configuration variables.
 - Some methods need to be renamed to both be more accurate in describing what they do and to line up with the way that the DDQ MySQL Plugin was made.
 - Adding manual testing scripts for supported database.
 - Add topic support.
 - Adding config validation.

2016-10-31 17:06 UTC, fidian requested changes

2016-10-31 17:06 UTC, fidian commented on README.md
> +Also, servers might not be able to handle a certain number of processes, or you might only want to handle a few at a time, so setting the `createMessageCycleLimit` to a number will make it so only up
`maxProcessingMessages` was used to limit how many events bubbled out at a time.  It was unrelated to the `createMessageCycleLimit` issue.  I suspect that `maxProcessingMessages` should still be here and `createMessageCycleLimit` is a backend configuration setting and does not belong to ddq core.

2016-10-31 17:06 UTC, fidian commented on lib/ddq.js
> +                    ddqInstance.resumeListening();
Why `resumeListening()` instead of `startListening()`?  Why is there a concept of "paused by user"?  I don't understand the benefit from this additional complexity.

2016-10-31 17:06 UTC, fidian commented on lib/ddq.js
> +         * @param {Function} successCallback
Are these optional?

Is it expected that the end user will call them?

If so, maybe rename this one to `connectInternal()` and expose a standard node-style callback interface for `connect()`.  The callback should be optional for the methods you intend for others to call.  Alternately, you could default the `successCallback` to be the same as `errorCallback` ...

```
if (!errorCallback) {
    errorCallback = () => {};
}

if (!successCallback) {
    successCallback = errorCallback;
}
```

2016-10-31 17:06 UTC, fidian commented on lib/ddq.js
> +         * @param {Function} connectionCallback
This feels wrong to have two callbacks passed here and an optional string as the last parameter.

2016-10-31 17:06 UTC, fidian commented on package.json
> +        "ddq-backend-mock": "1.0.5",
Should be ^1.0.5

2016-10-31 17:06 UTC, fidian commented on script/manual-testing-config.js
> +    pollingDelayMs: 15000,
These are not alphabetized.

2016-10-31 17:06 UTC, fidian commented on script/mysql-commands.sh
> +mysql -u root -e "CREATE DATABASE testQueue;"
This should probably be a script of lots of SQL commands instead of multiple invocations of mysql.

```
mysql -u root < mysql-commands.sql
```

Then the SQL could also be improved with "DROP DATABASE IF EXISTS testQueue;" at the beginning, or you can make the SQL by creating this structure and using mysqldump to generate the SQL file, which also has the clauses to prevent errors.  It would also create the table properly in one go without the need to issue six "ALTER TABLE" commands.

2016-10-31 17:06 UTC, fidian commented on script/polling-heartbeat-test.js
> +
Why does this exist?

2016-10-31 17:06 UTC, fidian commented on script/polling-heartbeat-test.js
> +        instance.startListening();
You are totally banking on the mock being synchronous.  A comment noting this assumption should be added in case the mock is made asynchronous.

2016-10-31 17:06 UTC, fidian commented on script/send-message-test.js
> +            console.log("sendMessage completed. Time difference between time of call and completion:", Date.now() / 1000 - fnCallTime);
Why log the time?  If it is for testing that things were done in a set amount of time, then an expectation should be created so you know automatically if the test passes or fails.

2016-10-31 17:06 UTC, fidian commented on script/wrapped-message-tests.js
> +            console.log("Affected Rows", data.affectedRows);
Again, this looks like something you should assert so the automated tests can catch problems here.

2016-10-31 17:06 UTC, fidian commented on script/wrapped-message-tests.js
> +
Newline shouldn't exist.

2016-10-31 17:06 UTC, fidian commented on script/wrapped-message-tests.js
> +
Newline shouldn't exist.

2016-10-31 17:06 UTC, fidian commented on script/wrapped-message-tests.js
> +
Newline shouldn't exist.

2016-10-31 17:06 UTC, fidian commented on script/wrapped-message-tests.js
> +
Newline shouldn't exist.

2016-10-31 17:06 UTC, fidian commented on spec/lib/ddq.spec.js
> +            createMessageCycleLimit: 2
You changed `maxProcessingMessages` into `createMessageCycleLimit` and that didn't seem to break any tests.  Makes me wonder more about this variable and enforces my belief that this is incorrect in the core.  See my comment about the docs way earlier.

2016-10-31 17:16 UTC, GoogilyBoogily commented on script/polling-heartbeat-test.js
> +pollingTest();
Add a newline above this.

2016-10-31 17:18 UTC, GoogilyBoogily commented on script/send-message-test.js
> + * @param {Function} fn
Even though the function description has a description of what `fn` is, you should also put a description here too.

2016-10-31 17:18 UTC, GoogilyBoogily commented on script/send-message-test.js
> + * @param {Function} done
Should probably also have a description of what the function is here too.

2016-10-31 17:30 UTC, AbsentSemicolon commented on README.md
> +When the `data` event is triggered from the backend DDQ will use methods on the data received from the `backend`. These methods include: `heartbeat`, `requeue`, and `remove`. The only piece of inform
Need a comma after '... backend...' and one after '... processed...' in the last sentence.

2016-10-31 17:32 UTC, AbsentSemicolon commented on lib/ddq.js
> +                    ddqInstance.resumeListening();
We had put in a paused by user in case the user has paused wanting polling to happen, but there is still a process going on. Should be that the user pauses while something is being processed, then DDQ will stop once it's done with processing what it is.

2016-10-31 17:33 UTC, AbsentSemicolon commented on lib/ddq.js
> +            this.maxProcessingMessages = config.createMessageCycleLimit;
Why not name this the same as the config value? Might alleviate some confusion.

2016-10-31 17:36 UTC, AbsentSemicolon commented on script/send-message-test.js
> + * @throw {Error}
Should have a brief explanation of why it throws I think.

2016-10-31 17:37 UTC, GoogilyBoogily commented on script/wrapped-message-tests.js
> + * @param {Function} fn
Should probably have a description of this.

2016-10-31 17:39 UTC, lnagle93 commented on README.md
> +Also, servers might not be able to handle a certain number of processes, or you might only want to handle a few at a time, so setting the `createMessageCycleLimit` to a number will make it so only up
Not sure what I was thinking here. Changed back, not just here but in other places as well.

2016-10-31 17:51 UTC, lnagle93 commented on package.json
> +        "ddq-backend-mock": "1.0.5",
Fixed.

2016-10-31 17:51 UTC, lnagle commented on script/manual-testing-config.js
> +    pollingDelayMs: 15000,
Fixed.

2016-10-31 17:52 UTC, lnagle93 commented on script/polling-heartbeat-test.js
> +
Removed

2016-11-01 11:43 UTC, lnagle commented on lib/ddq.js
> +            this.maxProcessingMessages = config.createMessageCycleLimit;
It shouldn't've changed to begin with. Fixed

2016-11-01 11:47 UTC, lnagle93 commented on README.md
> +When the `data` event is triggered from the backend DDQ will use methods on the data received from the `backend`. These methods include: `heartbeat`, `requeue`, and `remove`. The only piece of inform
Added after processed. I don't think adding a comma after backend makes sense.

Also changed with to will.

2016-11-01 11:50 UTC, lnagle93 commented on script/wrapped-message-tests.js
> +
Removed.

2016-11-01 11:50 UTC, lnagle commented on script/wrapped-message-tests.js
> +
Removed.

2016-11-01 11:51 UTC, lnagle commented on script/wrapped-message-tests.js
> +
Removed.

2016-11-01 11:51 UTC, lnagle93 commented on script/wrapped-message-tests.js
> +
Removed.

2016-11-01 11:55 UTC, lnagle93 commented on spec/lib/ddq.spec.js
> +            createMessageCycleLimit: 2
You're right that it shouldn't've been changed in the core. `createMessageCycleLimit` should only be in the backend config. Fixed.

2016-11-01 11:55 UTC, lnagle93 commented on script/polling-heartbeat-test.js
> +pollingTest();
Fixed.

2016-11-01 11:56 UTC, lnagle93 commented on script/send-message-test.js
> + * @param {Function} fn
Added.

2016-11-01 11:58 UTC, lnagle commented on script/send-message-test.js
> + * @param {Function} done
Added.

2016-11-01 11:59 UTC, lnagle93 commented on script/send-message-test.js
> + * @throw {Error}
Added.

2016-11-01 12:00 UTC, lnagle93 commented on script/wrapped-message-tests.js
> + * @param {Function} fn
Added.

2016-11-01 13:32 UTC, lnagle93 commented on lib/ddq.js
> +         * @param {Function} successCallback
Fixed as suggested.

2016-11-01 13:47 UTC, lnagle93 commented on lib/ddq.js
> +         * @param {Function} connectionCallback
With the change to `.connect` that you outlined above, the `connectionCallback` is now optional. In addition, the other callback should have been kept as optional too, and is now changed back. It still seems a little odd to have three different optional values, two of which are callbacks, but I'm not sure I see a better way of handling this.

2016-11-01 14:21 UTC, lnagle93 commented on script/mysql-commands.sh
> +mysql -u root -e "CREATE DATABASE testQueue;"
Fixed.

2016-11-01 14:32 UTC, lnagle93 commented on script/send-message-test.js
> +            console.log("sendMessage completed. Time difference between time of call and completion:", Date.now() / 1000 - fnCallTime);
This was added based on a comment made when these scripts were still a part of the DDQ MySQL Plugin. 

If it'd be preferable to check that this completes within an acceptable amount of time, how much time would that be? Otherwise, if these aren't necessary, I'll take them out.

2016-11-01 14:41 UTC, lnagle93 commented on script/wrapped-message-tests.js
> +            console.log("Affected Rows", data.affectedRows);
Added an assert for when `heartbeat` and `requeue` are run. As the comment on 58 mentions, `data.affectedRows` should be zero for `remove`.

2016-11-01 14:46 UTC, lnagle commented on script/polling-heartbeat-test.js
> +        instance.startListening();
Added a combination of callbacks and setTimeouts to take care of this, rather than a comment.

2016-11-01 20:12 UTC, AbsentSemicolon commented
Looks good to me though we need to figure out why the tests are failing in Travis.

2016-11-01 22:13 UTC, GoogilyBoogily commented
Looks a-o-k!

2016-11-03 12:47 UTC, fidian requested changes
Tests are failing.  That needs to get corrected.

I didn't see the "run one thing at a time" code that we talked about earlier.

2016-11-03 12:47 UTC, fidian commented on lib/ddq.js
> +                    ddqInstance.resumeListening();
In reply to @AbsentSemicolon - We should simplify this.  Pausing is the exact same as stopping, so it is simpler to just support start/stop instead of start/pause/stop.

2016-11-03 12:47 UTC, fidian commented on lib/ddq.js
> +                errorCallback = () => {};
Isn't there a `noop` variable that is the exact same as the empty anonymous function?  I suggest, for consistency, to pick one throughout the file.

2016-11-03 12:47 UTC, fidian commented on lib/ddq.js
> +        pauseListening() {
No callback means there's no way to indicate that the pausing was finally successful.  It's not a synchronous operation, but one would assume it is synchronous because there's no callback.

2016-11-03 12:47 UTC, fidian commented on script/polling-heartbeat-test.js
> +        instance.startListening();
As I mentioned earlier, you shouldn't rely on a specific amount of time elapsing.  You should trigger the tests based on callbacks completing.  What if it takes 2.001 seconds to connect to the database?

2016-11-03 12:47 UTC, fidian commented on script/send-message-test.js
> +        throw new Error(err);
Add a newline above.

2016-11-03 12:47 UTC, fidian commented on script/send-message-test.js
> +            console.log("sendMessage completed. Time difference between time of call and completion:", Date.now() / 1000 - fnCallTime);
Not sure.  I would hope that it doesn't take more than a tenth of a second to connect to a local database and add a message, but that could trigger test failure on a heavily loaded system.

2016-11-03 12:47 UTC, fidian commented on script/wrapped-message-tests.js
> + * other testing functions. Starts next test after logging any errors.
How does this start the next test after logging errors?  I suspect the comment is wrong.

2016-11-03 12:47 UTC, fidian commented on script/wrapped-message-tests.js
> +        console.error(err);
It appears that an error count is not tallied.  Does this script return a failure status code when a test fails?

2016-11-03 12:47 UTC, fidian commented on script/wrapped-message-tests.js
> +            console.log("Affected Rows", data.affectedRows);
You don't assert that the value is correct.  Instead, you either don't validate (`remove`) or confirm it is truthy (`heartbeat` and `requeue`).

2016-11-03 12:51 UTC, lnagle93 commented on lib/ddq.js
> +                errorCallback = () => {};
Fixed.

2016-11-03 13:03 UTC, lnagle93 commented on script/send-message-test.js
> +        throw new Error(err);
Fixed.

2016-11-27 23:54 UTC, lnagle93 commented on script/polling-heartbeat-test.js
> +        instance.startListening();
Fixed.

2016-11-27 23:57 UTC, lnagle93 commented on script/wrapped-message-tests.js
> +            console.log("Affected Rows", data.affectedRows);
Fixed.

2016-11-27 23:57 UTC, lnagle commented on script/wrapped-message-tests.js
> + * other testing functions. Starts next test after logging any errors.
Fixed.

2016-11-28 00:02 UTC, lnagle93 commented on script/wrapped-message-tests.js
> +        console.error(err);
Added error counting. At the end of the tests it will log how many errors were tallied and run an assertion on errCount.

2016-12-15 16:17 UTC, closed without merging